# Étape 1 : image de développement Node.js
FROM node:18-alpine

# Créer et se placer dans le dossier de l'app
WORKDIR /app

# Copier uniquement les fichiers de configuration et installer les dépendances
COPY package*.json ./
RUN npm install

# Copier tout le reste du projet
COPY . .

# Exposer le port par défaut de Vite
EXPOSE 5173

# Lancer le serveur de développement
CMD ["npm", "run", "dev", "--", "--host"]
