# Étape 1 : Build Vue.js avec Node
FROM node:18 AS builder

WORKDIR /app
COPY . .

# Installe les dépendances et build l'app
RUN npm install
RUN npm run build

# Étape 2 : Serveur Nginx avec les fichiers compilés
FROM nginx:alpine

# Copie la conf nginx personnalisée
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Copie les fichiers générés depuis le builder
COPY --from=builder /app/dist /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
