# Build de l'application Vue.js
FROM node:18-alpine AS builder

WORKDIR /app

# Installer les dépendances
COPY package*.json ./
RUN npm install

# Copier le reste des fichiers et builder l'app
COPY . .
RUN npm run build

# Image Nginx pour servir l'app optimisée
FROM nginx:stable-alpine

# Supprime le fichier par défaut de configuration si présent
RUN rm -rf /etc/nginx/conf.d/default.conf

# Copie du fichier de config nginx custom
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Copier le build dans le dossier web Nginx
COPY --from=builder /app/dist /usr/share/nginx/html

# Exposer le port 80
EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
