version: "3.8"

services:
  mongo-auth:
    image: mongo:6
    volumes:
      - mongo_auth_data:/data/db
    networks:
      - backend
    restart: always

  mongo-product:
    image: mongo:6
    volumes:
      - mongo_product_data:/data/db
    networks:
      - backend
    restart: always

  mongo-order:
    image: mongo:6
    volumes:
      - mongo_order_data:/data/db
    networks:
      - backend
    restart: always

  auth-service:
    image: nathanlrq/auth-service:prod
    restart: always
    environment:
      - NODE_ENV=production
    env_file:
      - ./services/auth-service/.env.production
    depends_on:
      - mongo-auth
    networks:
      - backend

  product-service:
    image: nathanlrq/product-service:prod
    restart: always
    environment:
      - NODE_ENV=production
    env_file:
      - ./services/product-service/.env.production
    depends_on:
      - mongo-product
    networks:
      - backend

  order-service:
    image: nathanlrq/order-service:prod
    restart: always
    environment:
      - NODE_ENV=production
    env_file:
      - ./services/order-service/.env.production
    depends_on:
      - mongo-order
    networks:
      - backend

  vue-frontend:
    image: nathanlrq/vue-frontend:prod
    restart: always
    ports:
      - "80:80"
    depends_on:
      - auth-service
      - product-service
      - order-service
    networks:
      - backend

volumes:
  mongo_auth_data:
  mongo_product_data:
  mongo_order_data:

networks:
  backend:
    driver: overlay
    attachable: true
